// LOCALHOST
### Get all user
GET http://localhost:8080/user


### Get user by id
GET http://localhost:8080/user/6918c85354188ff139d39ed4


### Create user
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "firstName":"Kelvin",
    "lastName":"Ajibola",
    "email":"kelv.ajibola@yahoo.com",
    "favoriteColor":"Brown",
    "birthday":"23/10/2004"
}


### PUT user
PUT http://localhost:8080/user/6918c9a464826154547ab232 HTTP/1.1
content-type: application/json

{
  "firstName": "Kelvin",
  "lastName": "Ajibola",
  "email": "kel@gmail.com",
  "favoriteColor": "Gray",
  "birthday": "23/10/2025"
}

### DELETE user
DELETE http://localhost:8080/user/6918bf6a154e374a24c299f8 HTTP/1.1

// PRODUCTION Deploy
### Get all user
GET https://cse341-project1-p8ez.onrender.com/user


### Get user by id
GET https://cse341-project1-p8ez.onrender.com/user/6918c85354188ff139d39ed4


### Create user
POST https://cse341-project1-p8ez.onrender.com/user HTTP/1.1
content-type: application/json

{
    "firstName":"Blessing",
    "lastName":"Brown",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT user
PUT https://cse341-project1-p8ez.onrender.com/user/6918c85354188ff139d39ed4 HTTP/1.1
content-type: application/json

{
    "firstName":"Mitchell",
    "lastName":"Johnson",
    "email":"mitch@gmail.com",
    "favoriteColor":"Orange",
    "birthday":"06/12/1990"
}


### DELETE user
DELETE https://cse341-project1-p8ez.onrender.com/user/6918c85354188ff139d39ed4 HTTP/1.1